name = "ToyHamiltonians"
uuid = "55fe3b46-18db-4f9f-8097-3a39978e0329"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
IsApprox = "28f27b66-4bd8-47e7-9110-e2746eb8bed7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Distributions = "0.25.112"
IsApprox = "2"
LinearAlgebra = "1.6"
Random = "1.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
